import React from 'react';
import { HelpCircle, Cpu, GitBranch, Shield, Zap, Layers, Sparkles } from 'lucide-react';

export const HelpDocView: React.FC = () => {
  return (
    <div className="flex-1 overflow-y-auto p-6 md:p-8 space-y-8 max-w-4xl mx-auto w-full">
      <div className="border-b border-slate-800 pb-5">
        <div className="flex items-center gap-2">
          <HelpCircle className="w-5 h-5 text-cyan-400" />
          <h1 className="text-xl font-bold text-white tracking-tight">NexusAI Architecture & Documentation</h1>
        </div>
        <p className="text-xs text-slate-400 mt-1">
          Technical specifications on intelligent task decomposition, dynamic AI routing, and self-healing integration.
        </p>
      </div>

      <div className="space-y-6 text-xs text-slate-300 leading-relaxed">
        {/* Concept */}
        <section className="p-5 rounded-2xl border border-slate-800 bg-slate-900/40 space-y-3">
          <h2 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2">
            <Cpu className="w-4 h-4 text-cyan-400" />
            <span>1. Multi-Model Collaborative Paradigm</span>
          </h2>
          <p>
            Unlike monolithic AI code assistants that rely on a single model for all aspects of a project, NexusAI Studio operates as an autonomous development organization. Different models possess distinct strengths:
          </p>
          <ul className="list-disc pl-5 space-y-1.5 text-slate-400">
            <li><strong className="text-slate-200">Google Gemini 3.8 Flash:</strong> Rapid code generation, fast scaffolding, state synchronization, and live repair patches with 1M+ context window.</li>
            <li><strong className="text-slate-200">Anthropic Claude 3.7 Sonnet:</strong> UI/UX aesthetics, responsive Tailwind layouts, component micro-interactions, and visual harmony.</li>
            <li><strong className="text-slate-200">OpenAI GPT-4o:</strong> High-level system architecture, OpenAPI schema design, and modular contract definitions.</li>
            <li><strong className="text-slate-200">DeepSeek R1 Reasoner:</strong> Algorithmic logic, database schema normalization, indexing, and edge-case computation.</li>
            <li><strong className="text-slate-200">Google Gemini 3.1 Pro:</strong> Security audits, OWASP vulnerability detection, token hardening, and strict compliance verification.</li>
            <li><strong className="text-slate-200">Meta Llama 3.3 70B:</strong> Automated unit test generation, WCAG accessibility checks, and production documentation.</li>
          </ul>
        </section>

        {/* Task Decomposition */}
        <section className="p-5 rounded-2xl border border-slate-800 bg-slate-900/40 space-y-3">
          <h2 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2">
            <GitBranch className="w-4 h-4 text-cyan-400" />
            <span>2. Task Decomposition & Dependency Graph (DAG)</span>
          </h2>
          <p>
            When a project prompt is submitted, the Architect decomposes the request into 7 to 10 granular tasks. Each task specifies:
          </p>
          <ul className="list-disc pl-5 space-y-1 text-slate-400">
            <li>Target file paths (e.g. <code>src/types/index.ts</code>, <code>src/components/Dashboard.tsx</code>).</li>
            <li>Explicit prerequisites (dependencies that must complete first).</li>
            <li>Primary model selection and verified fallback model.</li>
          </ul>
          <p>
            Independent tasks (such as UI design tokens and database models) execute concurrently in parallel, while dependent tasks wait for prerequisite artifacts before execution.
          </p>
        </section>

        {/* Automated Code Integration */}
        <section className="p-5 rounded-2xl border border-slate-800 bg-slate-900/40 space-y-3">
          <h2 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2">
            <Layers className="w-4 h-4 text-cyan-400" />
            <span>3. Zero-Defect Code Integration Engine</span>
          </h2>
          <p>
            Code generated by disparate models is never naively concatenated. The Integration Engine maintains a shared virtual filesystem, resolves conflicting import paths, standardizes exports, ensures props match domain interfaces, and compiles the bundle into an interactive sandbox iframe.
          </p>
        </section>

        {/* Self-Healing Repair */}
        <section className="p-5 rounded-2xl border border-slate-800 bg-slate-900/40 space-y-3">
          <h2 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2">
            <Shield className="w-4 h-4 text-cyan-400" />
            <span>4. Automated Testing & Self-Healing Repairs</span>
          </h2>
          <p>
            Following integration, a 6-phase test suite checks syntax balance, TypeScript type contracts, mock service integrity, OWASP security (preventing unsanitized innerHTML or eval), WCAG 2.2 contrast, and build bundle efficiency. If a test fails, the Debugging Specialist model is triggered to generate an in-place patch without losing project context.
          </p>
        </section>
      </div>
    </div>
  );
};
